name: Build App For Win/Mac
on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - master
    tags:
      - '*.*.*'
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Setup Haxe environment
        uses: krdlab/setup-haxe@v1.1.6
        with:
          haxe-version: 4.2.4
      - run: |
          haxelib install electron 4.1.4
          haxelib install jQueryExtern
          haxelib install haxe-loader

      - name: npm install
        run: |
          npm install
          npm run build
          npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          name: ${{ matrix.os }}
          path: |
            dist/*.zip
            dist/*.exe
            dist/*.dmg

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          files: |
            dist/*.zip
            dist/*.exe
            dist/*.dmg